rizefir/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from rizefir.views import IndexView, AboutView

urlpatterns = [
    path("admin/", admin.site.urls),
    path('products/', include('rizefir.products.urls')),
    path('users/', include('rizefir.users.urls', namespace='users')),
    path('', IndexView.as_view(), name='index'),
    path('about/', AboutView.as_view(), name='about')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rizefir/users/urls.py
from django.contrib.auth.views import LogoutView, PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, reverse_lazy
from . import views
from .views import RegisterUser, ProfileUser, UserPasswordChange, EmailConfirmationSentView, UserConfirmEmailView, \
    EmailConfirmedView, EmailConfirmationFailedView

app_name = "users"

urlpatterns = [
    path("login/", views.LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('password_change/', UserPasswordChange.as_view(), name='password_change'),
    path('password_change/done/', PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'),
         name='password_change_done'),

    # path('register/', RegisterUser.as_view(), name='register'),
    path('register/', RegisterUser.as_view(), name='register'),
    path('email-confirmation-sent/', EmailConfirmationSentView.as_view(), name='email_confirmation_sent'),
    path('confirm-email/<str:uidb64>/<str:token>/', UserConfirmEmailView.as_view(), name='confirm_email'),
    path('email-confirmed/', EmailConfirmedView.as_view(), name='email_confirmed'),
    path('confirm-email-failed/', EmailConfirmationFailedView.as_view(), name='email_confirmation_failed'),
    
    path('profile/', ProfileUser.as_view(), name='profile'),
    path('password_reset/', PasswordResetView.as_view(
        template_name='users/password_reset_form.html',
        email_template_name='users/password_reset_email.html', success_url=reverse_lazy('users:password_reset_done')),
         name='password_reset'),
    path('password_reset/done', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('password_reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url=reverse_lazy('users:password_reset_complete')),
         name='password_reset_confirm'),
    path('password_reset/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

rizefir/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.


class User(AbstractUser):
    photo = models.ImageField(upload_to='users/%Y/%m/%d/', blank=True, null=True, verbose_name='Фотография')
    date_birth = models.DateTimeField(blank=True, null=True, verbose_name='Дата рождения')
    phone = models.TextField(blank=True, null=True, verbose_name='Номер телефона')

rizefir/users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm


class LoginUserForm(AuthenticationForm):
    # username = forms.CharField(label='Логин',
    #                            widget=forms.TextInput(attrs={'class': 'form-input'}))
    # password = forms.CharField(label='Пароль',
    #                            widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        model = get_user_model()
        fields = ['username', 'password']


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': "form-control"}))
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': "form-control"}))
    password2 = forms.CharField(label='Повтор пароля', widget=forms.PasswordInput(attrs={'class': "form-control"}))

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2']
        labels = {'email': 'E-mail',
                  'first_name': 'Имя',
                  'last_name': 'Фамилия'
                  }
        widgets = {'email': forms.TextInput(attrs={'class': "form-control"}),
                   'first_name': forms.TextInput(attrs={'class': "form-control"}),
                   'last_name': forms.TextInput(attrs={'class': "form-control"})
                   }

    def clean_email(self):
        """Проверка email на уникальность"""
        email = self.cleaned_data['email']
        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError('Такой E-mail уже существует!')
        return email


class ProfileUserForm(forms.ModelForm):
    username = forms.CharField(disabled=True, label='Логин', widget=forms.TextInput(attrs={'class': "form-control"}))
    email = forms.CharField(disabled=True, label='E-mail', widget=forms.TextInput(attrs={'class': "form-control"}))
    

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name']
        labels = {
            'first_name': 'Имя',
            'last_name': 'Фамилия'
        }
        widgets = {
            'first_name': forms.TextInput(attrs={'class': "form-control"}),
            'last_name': forms.TextInput(attrs={'class': "form-control"})
        }


class UserPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(label=("Старый пароль"),
                                   widget=forms.PasswordInput(attrs={'class': "form-control"}))
    new_password1 = forms.CharField(label=("Новый пароль"),
                                    widget=forms.PasswordInput(attrs={'class': "form-control"}))
    new_password2 = forms.CharField(label=("Подтверждение пароля"),
                                    widget=forms.PasswordInput(attrs={'class': "form-control"}))

rizefir/users/views.py
from django.views.generic import TemplateView, View
from django.contrib.auth import get_user_model, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.views import LoginView, PasswordChangeView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.sites.models import Site
from django.core.mail import send_mail
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.shortcuts import redirect

from .mixins import UserIsNotAuthenticated

# Create your views here.
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, UpdateView

from .forms import LoginUserForm, RegisterUserForm, ProfileUserForm, UserPasswordChangeForm


class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'users/login.html'
    extra_context = {'title': 'Авторизация'}


class RegisterUser(UserIsNotAuthenticated, CreateView):
    """
    Представление регистрации на сайте с формой регистрации
    """
    form_class = RegisterUserForm
    template_name = 'users/register.html'
    extra_context = {'title': 'Регистрация'}
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = False
        user.save()
        # Функционал для отправки письма и генерации токена
        token = default_token_generator.make_token(user)
        uid = urlsafe_base64_encode(force_bytes(user.pk))
        activation_url = reverse_lazy('users:confirm_email', kwargs={'uidb64': uid, 'token': token})
        current_site = Site.objects.get_current().domain
        print(current_site)
        send_mail(
            'Подтвердите свой электронный адрес',
            f'Пожалуйста, перейдите по следующей ссылке, чтобы подтвердить свой адрес электронной '
            f'почты: http://{current_site}{activation_url}',
            'service.notehunter@gmail.com',
            [user.email],
            fail_silently=False,

        )
        return redirect('users:email_confirmation_sent')


# {{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}

class UserConfirmEmailView(View):
    def get(self, request, uidb64, token):
        try:
            uid = urlsafe_base64_decode(uidb64)
            user = get_user_model().objects.get(pk=uid)
            print(f'{uid}, {user}')
        except (TypeError, ValueError, OverflowError, get_user_model().DoesNotExist):
            user = None

        if user is not None and default_token_generator.check_token(user, token):
            user.is_active = True
            user.save()
            login(request, user, backend='django.contrib.auth.backends.ModelBackend')
            return redirect('users:email_confirmed')
        else:
            return redirect('users:email_confirmation_failed')


class EmailConfirmationSentView(TemplateView):
    template_name = 'users/email_confirmation_sent.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Письмо активации отправлено'
        return context


class EmailConfirmedView(TemplateView):
    template_name = 'users/email_confirmed.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Ваш электронный адрес активирован'
        return context


class EmailConfirmationFailedView(TemplateView):
    template_name = 'users/email_confirmation_failed.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Ваш электронный адрес не активирован'
        return context


class ProfileUser(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    form_class = ProfileUserForm
    template_name = 'users/profile.html'
    extra_context = {'title': 'Профиль пользователя'}

    def get_success_url(self):
        return reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user


class UserPasswordChange(PasswordChangeView):
    form_class = UserPasswordChangeForm
    success_url = reverse_lazy('users:password_change_done')
    template_name = 'users/password_change_form.html'

templates/users/email_confirmation_failed.html
{% extends "rizefir/base_layer.html" %}
{% load static %}
{% load i18n %}
{% block content %}
<div class="alert alert-danger" role="alert">
    <h4 class="alert-heading">Ошибка подтверждения по электронной почте</h4>
    <p>Ссылка для подтверждения по электронной почте недействительна или срок ее действия истек. Пожалуйста, зарегистрируйтесь снова.</p>
</div>
{% endblock %}

templates/users/email_confirmation_sent.html
{% extends "rizefir/base_layer.html" %}
{% load static %}
{% load i18n %}
{% block content %}
<div class="alert alert-info" role="alert">
    <h4 class="alert-heading">Письмо подтверждения отправлено!</h4>
    <p>
        На ваш адрес электронной почты было отправлено письмо с подтверждением. Пожалуйста, проверьте свою электронную почту и нажмите на ссылку подтверждения, чтобы завершить регистрацию.
        Если письмо не пришло, проверьте папку спам.
    </p>
</div>
{% endblock %}

templates/users/email_confirmed.html
{% extends "rizefir/base_layer.html" %}
{% load static %}
{% load i18n %}
{% block content %}
<div class="alert alert-success" role="alert">
    <h4 class="alert-heading">Электронная почта подтверждена</h4>
    <p>Ваш адрес электронной почты успешно подтвержден. Спасибо за регистрацию!</p>
</div>
{% endblock %}

templates/users/login.html
{% extends "rizefir/base_layer.html" %}
{% load static %}
{% load i18n %}
{% block content %}

<section class="container login">
  <div class="container-fluid h-custom">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-md-9 col-lg-6 col-xl-5">
        <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/draw2.webp"
          class="img-fluid" alt="Sample image">
      </div>
      <div class="col-md-8 col-lg-6 col-xl-4 offset-xl-1">
        <form method="post">
            {% csrf_token %}
          <div class="d-flex flex-row align-items-center justify-content-center justify-content-lg-start">
            <p class="lead fw-normal mb-0 me-3">Войти с помощью</p>
            <button type="button" class="btn btn-primary btn-floating mx-1">
              <i class="fab fa-facebook-f">ВК</i>
            </button>

            <button type="button" class="btn btn-primary btn-floating mx-1">
              <i class="fab fa-twitter"></i>
            </button>

            <button type="button" class="btn btn-primary btn-floating mx-1">
              <i class="fab fa-linkedin-in"></i>
            </button>
          </div>

          <div class="divider d-flex align-items-center my-4">
            <p class="text-center fw-bold mb-0">-------------  Или  -----------------</p>
          </div>
          {% if form.errors %}
            <p>Пожалуйста, введите правильные имя пользователя и пароль. Оба поля могут быть чувствительны к регистру.</p>
          {% endif %}
          <!-- Email input -->
          <div class="form-outline mb-4">
            <label class="form-label" for="form3Example3">Имя пользователя или e-mail:</label>
            <input type='text' id="form3Example3" class="form-control form-control-lg"
              placeholder="Введите имя пользователя" name="username"/>
          </div>
          

          <!-- Password input -->
          <div class="form-outline mb-3">
            <label class="form-label" for="form3Example4">Пароль:</label>
            <input type="password" id="form3Example4" class="form-control form-control-lg"
              placeholder="Введите пароль" name="password" />
          </div>

          <div class="d-flex justify-content-between align-items-center">
            <!-- Checkbox -->
            <a href="{% url 'users:password_reset' %}" class="text-body bor-bottom">Забыли пароль?</a>
          </div>

          <div class="text-center text-lg-start mt-4 pt-2">
            <button type="submit" class="btn btn-primary btn-lg w-100"
              >Войти</button>
            <p class="small fw-bold mt-2 pt-1 mb-0 ">Не зарегистрировались? <a href="{% url 'users:register' %}"
                class="link-danger">Регистрация</a></p>
            
          </div>

        </form>
      </div>
    </div>
  </div>


</section>


{% endblock %}

templates/users/password_change_done.html
{% extends "rizefir/base_layer.html" %}
{% load static %}
{% load i18n %}
{% block content %}

<section class="container login">
  <div class="container h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-lg-12 col-xl-11">
        <div class="card text-black" style="border-radius: 25px;">
          <div class="card-body p-md-5">
            <div class="row justify-content-center">
              <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">

                <p class="text-center fw-bold mb-5 mx-1 mx-md-4 mt-4">Пароль успешно изменен!</p>
                <p class="text-center fw-bold mb-5 mx-1 mx-md-4 mt-4">
                  <a href="{% url 'users:profile' %}">Вернуться в профиль</a></p>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>


{% endblock %}

templates/users/password_change_form.html
{% extends "rizefir/base_layer.html" %}
{% load static %}
{% load i18n %}
{% block content %}

<section class="container login">
  <div class="container h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-lg-12 col-xl-11">
        <div class="card text-black" style="border-radius: 25px;">
          <div class="card-body p-md-5">
            <div class="row justify-content-center">
              <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">

                <p class="text-center h2 fw-bold mb-5 mx-1 mx-md-4 mt-4">Изменение пароля</p>

                <form method="post" class="mx-1 mx-md-4 justify-content-center">
                  {% csrf_token %}
                  <input type="hidden" name="text" value="{{ next }}"/>
                  <div class="errors">{{ form.non_field_errors }}</div>
                  {% for f in form %}
                  <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
                  <div class="errors">{{ f.errors }}</div>
                  {% endfor %}
                  <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                    <button type="submit" class="btn btn-primary btn-lg">Изменить пароль</button>
                  </div>
                
              </div>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>


{% endblock %}

templates/users/password_reset_complete.html
{% extends "rizefir/base_layer.html" %}
{% load static %}
{% load i18n %}
{% block content %}

<section class="container login">
  <div class="container h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-lg-12 col-xl-11">
        <div class="card text-black" style="border-radius: 25px;">
          <div class="card-body p-md-5">
            <div class="row justify-content-center">
              <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">

                <p class="text-center h3 fw-bold mb-5 mx-1 mx-md-4 mt-4">Пароль изменен</p>
                <p class="text-center h3 fw-bold mb-5 mx-1 mx-md-4 mt-4">Поздравляем! Вы успешно изменили пароль 
                    своего аккаунта, используйте его для 
                    <a href="{% url 'users:login' %}">входа в систему</a></p>
                
              </div>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>


{% endblock %}

templates/users/password_reset_confirm.html
{% extends "rizefir/base_layer.html" %}
{% load static %}
{% load i18n %}
{% block content %}

<section class="container login">
  <div class="container h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-lg-12 col-xl-11">
        <div class="card text-black" style="border-radius: 25px;">
          <div class="card-body p-md-5">
            <div class="row justify-content-center">
              <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">

                
                {% if form %}
                <p class="text-center h2 fw-bold mb-5 mx-1 mx-md-4 mt-4">Новый пароль</p>
                
                <form method="post" class="mx-1 mx-md-4 justify-content-center">
                  {% csrf_token %}
                  <input type="hidden" name="text" value="{{ next }}"/>
                  <div class="errors">{{ form.non_field_errors }}</div>
                  {% for f in form %}
                  <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
                  <div class="errors">{{ f.errors }}</div>
                  {% endfor %}
                  <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                    <button type="submit" class="btn btn-primary btn-lg">Сохранить</button>
                  </div>
                  {% else %}
                  
                  <p class="text-center fw-bold mb-5 mx-1 mx-md-4 mt-4">Данная ссылка недействительна</p>
                  
                  {% endif %}
                
              </div>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>


{% endblock %}

templates/users/password_reset_done.html
{% extends "rizefir/base_layer.html" %}
{% load static %}
{% load i18n %}

{% block content %}

<h1>Сброс пароля</h1>

<p>{% translate 'We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.' %}</p>

<p>{% translate 'If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.' %}</p>

{% endblock %}

templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

templates/users/password_reset_form.html
{% extends "rizefir/base_layer.html" %}
{% load static %}
{% load i18n %}
{% block content %}

<section class="container login">
  <div class="container h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-lg-12 col-xl-11">
        <div class="card text-black" style="border-radius: 25px;">
          <div class="card-body p-md-5">
            <div class="row justify-content-center">
              <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">

                <p class="text-center h2 fw-bold mb-5 mx-1 mx-md-4 mt-4">Восстановление пароля</p>

                <form method="post" class="mx-1 mx-md-4">
                  {% csrf_token %}
                  <input type="hidden" name="text" value="{{ next }}"/>
                  <div class="errors">{{ form.non_field_errors }}</div>
                  {% for f in form %}
                  <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
                  <div class="errors">{{ f.errors }}</div>
                  {% endfor %}
                  <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                    <button type="submit" class="btn btn-primary btn-lg">Сбросить по E-mail</button>
                  </div>
                
              </div>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>


{% endblock %}

templates/users/profile.html
{% extends "rizefir/base_layer.html" %}
{% load static %}
{% load i18n %}
{% block content %}

<section class="container login">
  <div class="container h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-lg-12 col-xl-11">
        <div class="card text-black" style="border-radius: 25px;">
          <div class="card-body p-md-5">
            <div class="row justify-content-center">
              <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">

                <p class="text-center h2 fw-bold mb-5 mx-1 mx-md-4 mt-4">Профиль {{user.username}}</p>

                <form method="post" class="mx-1 mx-md-4">
                  {% csrf_token %}
                  <input type="hidden" name="text" value="{{ next }}"/>
                  <div class="errors">{{ form.non_field_errors }}</div>
                  {% for f in form %}
                  <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
                  <div class="errors">{{ f.errors }}</div>
                  {% endfor %}
                  <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                    <button type="submit" class="btn btn-primary btn-lg">Сохранить изменения</button>
                  </div>
                
                </form>
                <hr>
                <div class="text-center">
                <p ><a href="{% url 'users:password_change' %}">Сменить пароль</a></p>
                </div>
              </div>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>


{% endblock %}

templates/users/register.html
{% extends "rizefir/base_layer.html" %}
{% load static %}
{% load i18n %}
{% block content %}

<section class="container login">
  <div class="container h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-lg-12 col-xl-11">
        <div class="card text-black" style="border-radius: 25px;">
          <div class="card-body p-md-5">
            <div class="row justify-content-center">
              <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">

                <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Регистрация</p>

                <form method="post" class="mx-1 mx-md-4">
                  {% csrf_token %}
                  <input type="hidden" name="text" value="{{ next }}"/>
                  <div class="errors">{{ form.non_field_errors }}</div>
                  {% for f in form %}
                  <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
                  <div class="errors">{{ f.errors }}</div>
                  {% endfor %}
                  <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                    <button type="submit" class="btn btn-primary btn-lg">Зарегистрироваться</button>
                  </div>
                
                </form>
                
              </div>
              <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">

                <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-registration/draw1.webp"
                  class="img-fluid" alt="Sample image">

              </div>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>


{% endblock %}

templates/users/register_short.html
{% extends "rizefir/base_layer.html" %}
{% load static %}
{% load i18n %}
{% block content %}

<h1>Регистрация</h1>

<form method="post" class="mx-1 mx-md-4">
  {% csrf_token %}
  <input type="hidden" name="text" value="{{ next }}"/>
  <div class="errors">{{ form.non_field_errors }}</div>
  {% for f in form %}
  <p><label class="form-check" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
  <div class="errors">{{ f.errors }}</div>
  {% endfor %}
  <p><button type="submit">Регистрация</button></p>

</form>

</div>
                
                
                <form method="post" class="mx-1 mx-md-4">
                  {% csrf_token %}
                  {% for errors in form.errors %}
                    <p>{{ errors }}</p>
                  {% endfor %}
                  <div class="d-flex flex-row align-items-center mb-4">
                    <div class="form-outline flex-fill mb-0">
                      <input type="text" id="form3Example1c" class="form-control" name="username" />
                      <label class="form-label" for="form3Example1c">Ваше Имя</label>
                    </div>
                  </div>

                  <div class="d-flex flex-row align-items-center mb-4">
                    <div class="form-outline flex-fill mb-0">
                      <input type="email" id="form3Example2c" class="form-control" name="email" />
                      <label class="form-label" for="form3Example2c">Ваш Email</label>
                    </div>
                  </div>
                  
                   <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-envelope fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                      <input type="text" id="form3Example3c" class="form-control" name="first_name" />
                      <label class="form-label" for="form3Example3c">Ваше Имя</label>
                    </div>
                  </div>
                  
                   <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-envelope fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                      <input type="text" id="form3Example4c" class="form-control" name='last_name' />
                      <label class="form-label" for="form3Example4c">Ваша Фамилия</label>
                    </div>
                  </div>

                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-lock fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                      <input type="password" id="form3Example5c" class="form-control" name="password1" />
                      <label class="form-label" for="form3Example5c">Пароль</label>
                    </div>
                  </div>

                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-key fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                      <input type="password" id="form3Example4cd" class="form-control" name="password2" />
                      <label class="form-label" for="form3Example4cd">Повтор пароля</label>
                    </div>
                  </div>

                  <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                    <button type="submit" class="btn btn-primary btn-lg">Зарегистрироваться</button>
                  </div>

                </form>

              </div>
              <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">

                <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-registration/draw1.webp"
                  class="img-fluid" alt="Sample image">

              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>



{% endblock %}